@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(User, "Пользователь", "Пользователь приложения Теплый дом")
Person(Specialist, "Специалист", "Специалист по подключению системы отопления в доме к текущей версии системы")

System(SmartHome, "Smart Home", "Система управления Теплый дом")

System_Boundary(House, "Дом") {
    System_Ext(Sensor, "Датчик температуры")
    System_Ext(Warmer, "Контроллер отопления")
}

Rel(User, SmartHome, "Использует систему")
Rel(SmartHome, Sensor, "Запрос показаний датчика")
Rel(Sensor, SmartHome, "Регистрация датчика при включении")
Rel(SmartHome, Warmer, "Управление отоплением")
Rel(Specialist, Sensor, "Подключает к системе")
Rel(Specialist, Warmer, "Подключает к системе")

@enduml